apiVersion: v1
kind: Service
metadata:
  name: bdr-service3
  namespace: bdrnamespace
  labels:
    app: BDR_JAVA-TIERS
spec:
  selector:
    app: bdr-app
  ports:
  - protocol: TCP
    port: 30030
    targetPort: 30030
    nodePort: 30030
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdr3
  namespace: bdrnamespace
  labels:
    app: bdr-app
    framework: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdr-app
  template:
    metadata:
      labels:
        app: bdr-app
        framework: java
        tier: tier3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: bdr3
        image: docker.io/aslabs/bdr-tier3:latest
        ports:
        - containerPort: 30030
