apiVersion: v1
kind: Service
metadata:
  name: bdr-service2
  namespace: bdrnamespace
  labels:
    app: BDR_JAVA-TIERS
spec:
  selector:
    app: bdr-app
  ports:
  - protocol: TCP
    port: 30020
    targetPort: 30020
    nodePort: 30020
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdr2
  namespace: bdrnamespace
  labels:
    app: bdr-app
    framework: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdr-app
  template:
    metadata:
      labels:
        app: bdr-app
        framework: java
        tier: tier2
    spec:
      hostAliases:
      - ip: "192.168.49.2"
        hostnames:
        - "tier3"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: bdr2
        image: docker.io/aslabs/bdr-tier2:latest
        ports:
        - containerPort: 30020
